# Site settings
title: stuyCTF

destination: /srv/http/ctf
exclude: ['coffee', 'node_modules']

mode: development # set to production to enable analytics

# Build settings
markdown: kramdown
permalink: none

start_time: Month Day, Year
end_time: Month Day, Year
