# Site settings
title: stuyCTF

destination: /srv/http/ctf
exclude: ['coffee', 'node_modules']

mode: development # set to production to enable analytics

# Build settings
markdown: kramdown
permalink: none
