# Site settings
title: stuyCTF

destination: /srv/http/ctf
exclude: ['coffee', 'node_modules']

mode: production # set to production to enable analytics

# Build settings
markdown: kramdown
permalink: none

start_time: April 11, 2015 10:00 AM
end_time: April 20, 2015 10:00 PM
